apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sample-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ubuntu
              image: ubuntu
              command:
                - "bin/bash"
                - "-c"
                - "date"
          restartPolicy: Never
