apiVersion: batch/v1
kind: Job
metadata:
  name: sample-program
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command:
         - "bin/bash"
         - "-c"
         - "for (( i=1; i<=10; i++ )) ; do echo $i ; done"
      restartPolicy: Never
